rundll32 printui.dll,PrintUIEntry /dl /n "Fax" /q
rundll32 printui.dll,PrintUIEntry /dl /n "Invia a OneNote 2013" /q
rundll32 printui.dll,PrintUIEntry /dl /n "Invia a OneNote 2010" /q
rundll32 printui.dll,PrintUIEntry /dl /n "Invia a OneNote 2016" /q
rundll32 printui.dll,PrintUIEntry /dl /n "Invia a OneNote 16" /q
rundll32 printui.dll,PrintUIEntry /dl /n "OneNote 2016" /q
rundll32 printui.dll,PrintUIEntry /dl /n "Invia a OneNote" /q
rundll32 printui.dll,PrintUIEntry /dl /n "OneNote 16" /q
rundll32 printui.dll,PrintUIEntry /dl /n "OneNote" /q
rundll32 printui.dll,PrintUIEntry /dl /n "Microsoft XPS Document Writer" /q
del "%USERPROFILE%\Desktop\%~nx0"
